name: android_app_checker
description: "Flutter plugin for safe Android app verification without 'QUERY_ALL_PACKAGES' permission, aligning with Google Play privacy standards."

version: 0.0.4
maintainer: Dmitriy Trofimov
homepage: https://github.com/a-dev-mobile/android_app_checker
repository: https://github.com/a-dev-mobile/android_app_checker/
issue_tracker: https://github.com/a-dev-mobile/android_app_checker/issues

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:

  plugin:
    platforms:
      android:
        package: com.wayofdt.android_app_checker
        pluginClass: AndroidAppCheckerPlugin

