name: android_app_checker
description: "Android App Checker is an innovative Flutter plugin designed for efficiently determining the presence of installed applications on Android devices without requiring the extensive 'QUERY_ALL_PACKAGES' permission. This tool offers a privacy-centric approach, significantly reducing the scope of permissions needed, thereby aligning with the latest Google Play Store guidelines and enhancing user trust. Ideal for developers looking to maintain functionality while adhering to privacy standards, this plugin is easy to integrate and use in any Flutter project. It provides a streamlined method to check installed applications, ensuring your app remains compliant and secure."
version: 0.0.1
maintainer: Dmitriy Trofimov
homepage: https://github.com/a-dev-mobile/android_app_checker
repository: https://github.com/a-dev-mobile/android_app_checker/
issue_tracker: https://github.com/a-dev-mobile/android_app_checker/issues

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.wayofdt.android_app_checker
        pluginClass: AndroidAppCheckerPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
